name: Secret Environment Variable Test

on:
  push:

jobs:
  use-secret-env:
    runs-on: ubuntu-latest

    steps:
      - name: Use secrets as environment variables
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

        run: |
          echo "Using Docker credentials securely"
          echo "Docker username is set"