name: Self Hosted Runner Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Runner check
        run: echo "Self Hosted Runner Working"

      - name: System info
        run: |
          uname -a
          hostname
          whoami
