name: Self Hosted Runner Test

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Print message
        run: echo "Self Hosted Runner Working"

      - name: Show system info
        run: |
          hostname
          whoami
          uname -a
